### ISSUE TITLE
add LICENSE file

### ISSUE THREAD

**Issue by dmitris** [gophergala/go_report#17]
Could you add licensing information, please?  I did not see the LICENSE file and it is not clear whether the code may be used and under which license.  I would also recommend to add Copyright line to files such as .go.

**Comment by shawnps** [comment]
Hi @dmitris,

Development of Go Report Card will continue here, where this is a LICENSE file:

https://github.com/gojp/goreportcard

**Comment by abduelhamit** [comment]
Please write that in the README so it's easy to find.

**Comment by hermanschaaf** [comment]
I added it to the readme, and will now move the issues here over to that repository. Thanks for reporting!
